### ISSUE TITLE
책 검색 방법

### ISSUE THREAD

**Issue by humit0** [wixsoft/Bodleian#3]
## Yes24
http://m.yes24.com/search/result 에 "query=9791156641131&page=1&sort=POPULAR&domain=ALL&salestat=ALL"를 post data로 전송한 후 `em.class > a`의 링크를 가져오면 됨 여기서 query 부분은 isbn을 입력하면 하나의 데이터만 얻을 수 있다. 저장할 값은 링크의 숫자만 저장하면 된다.
## Interpark
공식적으로 제공하는 API를 사용가능. 저장할 값은 링크의 숫자만 저장하면 된다.
## 알라딘
공식적으로 제공하는 API를 사용가능. 혹은 http://www.aladin.co.kr/m/mproduct.aspx?ISBN={isbn} 으로 바로 사용 가능. isbn만 알고 있으면 되므로 추가적으로 저장할 값은 없다.
## 교보문고
http://mobile.kyobobook.co.kr/search/main/{isbn} 으로 사용 가능. 언어코드를 저장해야 한다.(`KOR`, `BNT` 등)

**Comment by webhacking** [comment]
isbn을 유니크한 키로 지정하고, 봇을 돌리는데 크롤링할 기준 인덱스를 정하기 애매하네.

**Comment by humit0** [comment]
http://m.yes24.com/Goods/DetailView?goodsNo=13776831&contentsType=CONSTITUTION -> 목차

"http://m.yes24.com/Goods/Detail/13776831"
-> em.yes_m 정가, 판매가, 포인트
-> span.txt_deli 배송비

**Comment by humit0** [comment]
http://m.book.naver.com/bookdb/book_detail.nhn?biblio.bid=7820969
네이버 책 검색을 이용하면 한 번에 가격 정보 및 적립 금액, 배송비에 대한 항목을 알아낼 수 있다.

**Comment by webhacking** [comment]
굿굿.
