### ISSUE TITLE
로그인,회원가입 부분 레이아웃

### ISSUE THREAD

**Issue by webhacking** [wixsoft/Bodleian#9]
기존 기획 상, 우측 상단이었는데 우측상단으로 그냥 진행할까?
근데 애로 사항이 꼭 검색 `input` 을 `focus` 해야만 노출된다는 것..

**Comment by humit0** [comment]
그런 경우라면 다른 위치로 옮기는 편이 더 나을 수도 있겠음... 검색 `input`을 클릭하지 않았을 떄도 링크가 보여져야 할 것 같아서...

**Comment by webhacking** [comment]
아 그렇긴한데, `focus` 될때를 기점으로 display 하는건 좀 생각할수록 웃기긴하네 ㅋㅋ;

**Comment by webhacking** [comment]
수정함
